import type {
  CatalogRow,
  EventItem,
  FactoryTireGroup,
  FullOrder,
  GoodsItem,
  MyListing,
  Notice,
  Order,
  Seller,
  Tire,
  TireSpec,
  WishSeller,
} from "./types";

export const MANUFACTURERS = [
  "금호",
  "한국",
  "넥센",
  "미쉐린",
  "피렐리",
  "콘티넨탈",
  "브리지스톤",
  "굿이어",
  "던롭",
] as const;

export const TIRES: Tire[] = [
  {
    id: "t1",
    manufacturer: "콘티넨탈",
    model: "ExtremeContact DWS06 plus",
    width: 255,
    ratio: 40,
    rim: 18,
    dot: "2025",
    discountRate: 50,
    price: 212300,
    tag: "EVENT",
    stock: 12,
  },
  {
    id: "t2",
    manufacturer: "콘티넨탈",
    model: "ExtremeContact DWS06 plus",
    width: 275,
    ratio: 30,
    rim: 20,
    dot: "2025",
    discountRate: 55,
    price: 303190,
    tag: "EVENT",
    stock: 6,
  },
  {
    id: "t3",
    manufacturer: "콘티넨탈",
    model: "ComfortContact CC7",
    width: 165,
    ratio: 60,
    rim: 14,
    dot: "2025",
    discountRate: 55,
    price: 55900,
    tag: "EVENT",
    stock: 20,
  },
  {
    id: "t4",
    manufacturer: "콘티넨탈",
    model: "ComfortContact CC7",
    width: 205,
    ratio: 55,
    rim: 16,
    dot: "2025",
    discountRate: 55,
    price: 78200,
    tag: "EVENT",
    stock: 18,
  },
  {
    id: "t5",
    manufacturer: "콘티넨탈",
    model: "ProContact TX",
    width: 245,
    ratio: 40,
    rim: 19,
    dot: "2025",
    discountRate: 55,
    price: 166800,
    tag: "EVENT",
    stock: 9,
  },
  {
    id: "t6",
    manufacturer: "콘티넨탈",
    model: "UltraContact UC6",
    width: 245,
    ratio: 45,
    rim: 19,
    dot: "2026",
    discountRate: 57,
    price: 136200,
    tag: "EVENT",
    stock: 14,
  },
  {
    id: "t7",
    manufacturer: "한국",
    model: "Dynapro HPX (RA43)",
    width: 235,
    ratio: 55,
    rim: 19,
    dot: "2025",
    discountRate: 45,
    price: 132400,
    tag: "BEST",
    stock: 11,
  },
  {
    id: "t8",
    manufacturer: "한국",
    model: "Vantra DT (DU05)",
    width: 145,
    ratio: 80,
    rim: 13,
    dot: "2025",
    discountRate: 45,
    price: 41990,
    tag: "BEST",
    stock: 30,
  },
  {
    id: "t9",
    manufacturer: "한국",
    model: "Vantra LT (RA18)",
    width: 195,
    ratio: 80,
    rim: 15,
    dot: "2026",
    discountRate: 37,
    price: 83370,
    tag: "BEST",
    stock: 22,
  },
  {
    id: "t10",
    manufacturer: "콘티넨탈",
    model: "ContiCrossContact LX Sport",
    width: 235,
    ratio: 60,
    rim: 18,
    dot: "2025",
    discountRate: 56,
    price: 147280,
    tag: "BEST",
    stock: 7,
  },
  {
    id: "t11",
    manufacturer: "금호",
    model: "MARSHAL MC55",
    width: 145,
    ratio: 80,
    rim: 13,
    dot: "2026",
    discountRate: 47,
    price: 38980,
    tag: "BEST",
    stock: 25,
  },
  {
    id: "t12",
    manufacturer: "미쉐린",
    model: "PRIMACY TOUR AS",
    width: 245,
    ratio: 40,
    rim: 19,
    dot: "2026",
    discountRate: 40,
    price: 222990,
    tag: "BEST",
    stock: 5,
  },
  {
    id: "t13",
    manufacturer: "넥센",
    model: "N'Fera Sport",
    width: 225,
    ratio: 45,
    rim: 17,
    dot: "2025",
    discountRate: 30,
    price: 98000,
    tag: null,
    stock: 16,
  },
  {
    id: "t14",
    manufacturer: "피렐리",
    model: "P Zero",
    width: 255,
    ratio: 35,
    rim: 19,
    dot: "2025",
    discountRate: 20,
    price: 265000,
    tag: null,
    stock: 4,
  },
  {
    id: "t15",
    manufacturer: "브리지스톤",
    model: "Turanza T005",
    width: 205,
    ratio: 55,
    rim: 16,
    dot: "2026",
    discountRate: 25,
    price: 89000,
    tag: null,
    stock: 19,
  },
  {
    id: "t16",
    manufacturer: "콘티넨탈",
    model: "UltraContact UC6",
    width: 245,
    ratio: 45,
    rim: 18,
    dot: "2026",
    discountRate: 48,
    price: 158900,
    tag: null,
    stock: 18,
  },
  {
    id: "t17",
    manufacturer: "한국",
    model: "Ventus S2 AS (H462)",
    width: 245,
    ratio: 45,
    rim: 18,
    dot: "2025",
    discountRate: 44,
    price: 149800,
    tag: "BEST",
    stock: 26,
  },
  {
    id: "t18",
    manufacturer: "금호",
    model: "Majesty9 SOLUS TA91",
    width: 245,
    ratio: 45,
    rim: 18,
    dot: "2026",
    discountRate: 46,
    price: 142500,
    tag: null,
    stock: 31,
  },
];

export const EVENTS: EventItem[] = [
  {
    id: "e1",
    title: "장마철 공식 비수기 탈출",
    bannerGradient: "linear-gradient(135deg,#fef3c7,#fde68a)",
    status: "ongoing",
    period: "2026.07.01 ~ 2026.08.31",
    description:
      "타이어존이 사장님의 마진을 지킵니다. 장마철 비수기 전국 직영 물류 창고 재고를 특가로 만나보세요.",
  },
  {
    id: "e2",
    title: "콘티넨탈 빅 세일",
    bannerGradient: "linear-gradient(135deg,#f472b6,#a855f7)",
    status: "ongoing",
    period: "2026.07.10 ~ 2026.07.31",
    description: "콘티넨탈 인기 모델 전 품목 최대 57% 할인 이벤트입니다.",
  },
  {
    id: "e3",
    title: "봄맞이 신학기 할인전",
    bannerGradient: "linear-gradient(135deg,#86efac,#22d3ee)",
    status: "ended",
    period: "2026.03.01 ~ 2026.03.31",
    description: "신학기를 맞아 진행되었던 전 품목 할인 이벤트입니다.",
  },
];

export const EVENT_BANNER_IMAGES: Partial<Record<string, string>> = {
  e1: "/banners/rainy-season-ad.jpg",
  e2: "/banners/continental-big-sale.jpg",
};

export const ORDERS: Order[] = [
  {
    id: "278402",
    tireModel: "솔루스 TA31",
    status: "배송조회",
    orderedAt: "2026-07-20",
    price: 132400,
  },
  {
    id: "278357",
    tireModel: "솔루스 TA31",
    status: "입금후취소",
    orderedAt: "2026-07-19",
    price: 132400,
  },
  {
    id: "268623",
    tireModel: "Dynapro HPX (RA43)",
    status: "배송조회",
    orderedAt: "2026-07-02",
    price: 132400,
  },
  {
    id: "262827",
    tireModel: "Ventus S2 AS (H462)",
    status: "배송완료",
    orderedAt: "2026-06-18",
    price: 118900,
  },
];

export const NOTICES: Notice[] = [
  { id: "n1", title: "[공지] 타이어존 판매 수수료 변경 안내", date: "2026-06-30" },
  { id: "n2", title: "2026년 6월 1일 공장도가 변경 내역 (요코하마)", date: "2026-06-01" },
  { id: "n3", title: "2026년 6월 1일 공장도가 변경 내역 (피렐리)", date: "2026-06-01" },
  { id: "n4", title: "2025년 7월 1일 공장도가 인상 내역 (미쉐린)", date: "2025-07-01" },
  { id: "n5", title: "2025년 4월 15일 공장도가 인상 내역 (요코하마)", date: "2025-04-15" },
  { id: "n6", title: "2025년 4월 1일 공장도가 인상 내역 (던롭 타이어)", date: "2025-04-01" },
  { id: "n7", title: "2025년 4월 1일 공장도가 인상 내역 (콘티넨탈)", date: "2025-04-01" },
];

export const TIRE_SPECS: Record<string, TireSpec> = {
  t1: {
    loadIndex: "99",
    speedIndex: "Y",
    ply: "4P",
    origin: "프랑스",
    season: "사계절",
    productCode: "15573160000",
  },
  t2: {
    loadIndex: "97",
    speedIndex: "Y",
    ply: "4P",
    origin: "프랑스",
    season: "사계절",
    productCode: "15573160001",
  },
  t3: {
    loadIndex: "75",
    speedIndex: "H",
    ply: "4P",
    origin: "한국",
    season: "사계절",
    productCode: "15573160002",
  },
  t4: {
    loadIndex: "91",
    speedIndex: "V",
    ply: "4P",
    origin: "한국",
    season: "사계절",
    productCode: "15573160003",
  },
  t5: {
    loadIndex: "94",
    speedIndex: "V",
    ply: "4P",
    origin: "독일",
    season: "사계절",
    productCode: "15573160004",
  },
  t6: {
    loadIndex: "98",
    speedIndex: "W",
    ply: "4P",
    origin: "독일",
    season: "사계절",
    productCode: "15573160005",
  },
  t7: {
    loadIndex: "101",
    speedIndex: "H",
    ply: "4P",
    origin: "한국",
    season: "사계절",
    productCode: "15573160006",
  },
  t8: {
    loadIndex: "88",
    speedIndex: "R",
    ply: "8P",
    origin: "중국",
    season: "사계절",
    productCode: "15573160007",
  },
  t9: {
    loadIndex: "106",
    speedIndex: "R",
    ply: "8P",
    origin: "중국",
    season: "사계절",
    productCode: "15573160008",
  },
  t10: {
    loadIndex: "103",
    speedIndex: "H",
    ply: "4P",
    origin: "한국",
    season: "사계절",
    productCode: "15573160009",
  },
  t11: {
    loadIndex: "88",
    speedIndex: "R",
    ply: "8P",
    origin: "한국",
    season: "사계절",
    productCode: "15573160010",
  },
  t12: {
    loadIndex: "94",
    speedIndex: "W",
    ply: "4P",
    origin: "미국",
    season: "사계절",
    productCode: "15573160011",
  },
  t13: {
    loadIndex: "94",
    speedIndex: "Y",
    ply: "4P",
    origin: "한국",
    season: "사계절",
    productCode: "15573160012",
  },
  t14: {
    loadIndex: "96",
    speedIndex: "Y",
    ply: "4P",
    origin: "이탈리아",
    season: "사계절",
    productCode: "15573160013",
  },
  t15: {
    loadIndex: "91",
    speedIndex: "V",
    ply: "4P",
    origin: "일본",
    season: "사계절",
    productCode: "15573160014",
  },
};

export const SELLERS_BY_TIRE: Record<string, Seller[]> = {
  t1: [
    {
      code: "T22806",
      discountRate: 50,
      price: 212300,
      stock: 40,
      minOrder: 1,
      shippingNote: "오늘 출고 (오후 3시 30분까지 입금시)",
      courier: "대신택배",
    },
    {
      code: "T19042",
      discountRate: 47,
      price: 224900,
      stock: 12,
      minOrder: 1,
      shippingNote: "익일 출고",
      courier: "로젠택배",
    },
    {
      code: "T30115",
      discountRate: 44,
      price: 237600,
      stock: 3,
      minOrder: 2,
      shippingNote: "익일 출고 (2개 이상 주문시)",
      courier: "CJ대한통운",
    },
  ],
  t7: [
    {
      code: "T22510",
      discountRate: 45,
      price: 132400,
      stock: 28,
      minOrder: 1,
      shippingNote: "오늘 출고 (오후 3시까지 입금시)",
      courier: "대신택배",
    },
    {
      code: "T11837",
      discountRate: 41,
      price: 141200,
      stock: 9,
      minOrder: 1,
      shippingNote: "익일 출고",
      courier: "로젠택배",
    },
  ],
  t11: [
    {
      code: "T23124",
      discountRate: 47,
      price: 38980,
      stock: 60,
      minOrder: 4,
      shippingNote: "오늘 출고 (오후 3시까지 입금시)",
      courier: "대신택배",
    },
    {
      code: "T24549",
      discountRate: 43,
      price: 41500,
      stock: 15,
      minOrder: 1,
      shippingNote: "익일 출고",
      courier: "CJ대한통운",
    },
  ],
};

function defaultSellersFor(tire: Tire): Seller[] {
  return [
    {
      code: "T22806",
      discountRate: tire.discountRate,
      price: tire.price,
      stock: tire.stock,
      minOrder: 1,
      shippingNote: "오늘 출고 (오후 3시 30분까지 입금시)",
      courier: "대신택배",
    },
    {
      code: "T19042",
      discountRate: Math.max(tire.discountRate - 4, 5),
      price: Math.round((tire.price * 1.03) / 10) * 10,
      stock: Math.max(Math.round(tire.stock / 3), 1),
      minOrder: 1,
      shippingNote: "익일 출고",
      courier: "로젠택배",
    },
  ];
}

export function getSellersForTire(tire: Tire): Seller[] {
  return SELLERS_BY_TIRE[tire.id] ?? defaultSellersFor(tire);
}

export const FACTORY_TIRES: FactoryTireGroup[] = [
  {
    id: "f1",
    manufacturer: "넥센",
    model: "I.Q series1",
    width: 165,
    ratio: 60,
    rim: 14,
    spec: "75 H 4P 한국",
    factoryPrice: 77000,
    rows: [
      { dot: "2026", discountRate: 59, price: 31320, stock: 227 },
      { dot: "2025", discountRate: 30, price: 53900, stock: 13 },
    ],
  },
  {
    id: "f2",
    manufacturer: "넥센",
    model: "I.Q series1",
    width: 175,
    ratio: 50,
    rim: 15,
    spec: "75 H 4P 한국",
    factoryPrice: 92400,
    rows: [{ dot: "2026", discountRate: 60, price: 36950, stock: 1477 }],
  },
  {
    id: "f3",
    manufacturer: "금호",
    model: "크루젠 프리미엄 KL33",
    width: 235,
    ratio: 55,
    rim: 19,
    spec: "101 H 4P 한국 사계절",
    factoryPrice: 216700,
    rows: [],
  },
  {
    id: "f4",
    manufacturer: "한국",
    model: "Radial (RA08)",
    width: 195,
    ratio: 70,
    rim: 15,
    spec: "104/102 R 8P 포터2 중국",
    factoryPrice: 133100,
    rows: [
      { dot: "2026", discountRate: 38, price: 82000, stock: 143 },
      { dot: "2025", discountRate: 36, price: 84540, stock: 104 },
    ],
  },
  {
    id: "f5",
    manufacturer: "넥센",
    model: "ROADIAN GTX",
    width: 235,
    ratio: 55,
    rim: 19,
    spec: "101 H 4 투싼,스포티지",
    factoryPrice: 210100,
    rows: [
      { dot: "2026", discountRate: 57, price: 90980, stock: 787 },
      { dot: "2025", discountRate: 49, price: 107780, stock: 52 },
      { dot: "2023", discountRate: 37, price: 132830, stock: 1 },
    ],
  },
  {
    id: "f6",
    manufacturer: "한국",
    model: "Vantra DT (DU05)",
    width: 145,
    ratio: 80,
    rim: 13,
    spec: "88/86 R 8P 중국",
    factoryPrice: 75900,
    rows: [
      { dot: "2026", discountRate: 44, price: 42190, stock: 357 },
      { dot: "2025", discountRate: 45, price: 41990, stock: 174 },
    ],
  },
  {
    id: "f7",
    manufacturer: "미쉐린",
    model: "PRIMACY TOUR AS",
    width: 245,
    ratio: 50,
    rim: 20,
    spec: "102 V 4 팰리세이드 사계절용",
    factoryPrice: 389400,
    rows: [
      { dot: "2026", discountRate: 42, price: 225800, stock: 557 },
      { dot: "2025", discountRate: 36, price: 248000, stock: 41 },
      { dot: "2024", discountRate: 42, price: 225810, stock: 1 },
    ],
  },
  {
    id: "f8",
    manufacturer: "콘티넨탈",
    model: "ContiProContact",
    width: 245,
    ratio: 45,
    rim: 19,
    spec: "98 W 4P GOE 포르투갈",
    factoryPrice: 454300,
    rows: [
      { dot: "2026", discountRate: 46, price: 245000, stock: 6 },
      { dot: "2025", discountRate: 57, price: 197590, stock: 354 },
      { dot: "2023", discountRate: 42, price: 263450, stock: 50 },
    ],
  },
];

function specStringFor(tireId: string): string {
  const s = TIRE_SPECS[tireId];
  if (!s) return "-";
  return `${s.loadIndex} ${s.speedIndex} ${s.ply} ${s.origin}`;
}

function buildCatalog(): CatalogRow[] {
  const rows: CatalogRow[] = [];
  let order = 0;

  for (const t of TIRES) {
    const sellers = getSellersForTire(t);
    // Seller.price is `number | null` only because the shared type now models
    // the guest-gated API response; every literal in this mock file is a real
    // number, so the fallback never actually fires.
    const prices = sellers.map((s) => s.price ?? 0);
    rows.push({
      id: `row-${t.id}`,
      detailId: t.id,
      detailDot: null,
      manufacturer: t.manufacturer,
      model: t.model,
      width: t.width,
      ratio: t.ratio,
      rim: t.rim,
      spec: specStringFor(t.id),
      productCode: TIRE_SPECS[t.id]?.productCode ?? "-",
      dot: t.dot,
      factoryPrice: Math.round(t.price / (1 - t.discountRate / 100) / 100) * 100,
      lowPrice: Math.min(...prices),
      highPrice: Math.max(...prices),
      stock: t.stock,
      discountRate: t.discountRate,
      tag: t.tag,
      registeredOrder: order++,
    });
  }

  for (const g of FACTORY_TIRES) {
    for (const r of g.rows) {
      rows.push({
        id: `row-${g.id}-${r.dot}`,
        detailId: g.id,
        detailDot: r.dot,
        manufacturer: g.manufacturer,
        model: g.model,
        width: g.width,
        ratio: g.ratio,
        rim: g.rim,
        spec: g.spec,
        productCode: `${g.id}${r.dot}`.toUpperCase(),
        dot: r.dot,
        factoryPrice: g.factoryPrice,
        lowPrice: r.price,
        highPrice: r.price,
        stock: r.stock,
        discountRate: r.discountRate,
        tag: null,
        registeredOrder: order++,
      });
    }
  }

  return rows;
}

export const CATALOG: CatalogRow[] = buildCatalog();

export const FULL_ORDERS: FullOrder[] = [
  {
    id: "247137",
    orderNo: "247137",
    status: "구매확정",
    manufacturer: "금호",
    model: "솔루스 TA31",
    width: 175,
    ratio: 65,
    rim: 14,
    factoryPrice: 102300,
    unitPrice: 60000,
    quantity: 2,
    extraShipping: 0,
    total: 120000,
    sellerCode: "T24549",
    orderedAt: "2026-07-02 13:10",
  },
  {
    id: "247095",
    orderNo: "247095",
    status: "입금후취소",
    manufacturer: "금호",
    model: "솔루스 TA31",
    width: 175,
    ratio: 65,
    rim: 14,
    factoryPrice: 102300,
    unitPrice: 59990,
    quantity: 2,
    extraShipping: 0,
    total: 119980,
    sellerCode: "T23124",
    orderedAt: "2026-07-02 11:32",
  },
  {
    id: "238333",
    orderNo: "238333",
    status: "구매확정",
    manufacturer: "한국",
    model: "Dynapro HPX (RA43)",
    width: 265,
    ratio: 55,
    rim: 19,
    factoryPrice: 272800,
    unitPrice: 168240,
    quantity: 4,
    extraShipping: 0,
    total: 672960,
    sellerCode: "T22510",
    orderedAt: "2026-05-25 13:17",
  },
  {
    id: "233115",
    orderNo: "233115",
    status: "구매확정",
    manufacturer: "한국",
    model: "Ventus S2 AS (H462)",
    width: 225,
    ratio: 55,
    rim: 18,
    factoryPrice: 262900,
    unitPrice: 141900,
    quantity: 4,
    extraShipping: 0,
    total: 567600,
    sellerCode: "T23495",
    orderedAt: "2026-04-27 19:13",
  },
  {
    id: "232762",
    orderNo: "232762",
    status: "구매확정",
    manufacturer: "한국",
    model: "KINERGY ST AS (H318)",
    width: 185,
    ratio: 65,
    rim: 14,
    factoryPrice: 93500,
    unitPrice: 58390,
    quantity: 2,
    extraShipping: 0,
    total: 116780,
    sellerCode: "T22510",
    orderedAt: "2026-04-25 13:21",
  },
];

export const ORDER_STATUS_COUNTS = {
  입금대기: 0,
  입금완료: 0,
  주문확인: 0,
  배송준비중: 0,
  배송중: 0,
  배송완료: 0,
  구매확정: 4,
};

export const CANCEL_STATUS_COUNTS = {
  입금전취소: 0,
  입금후취소: 1,
  교환완료: 0,
  반품완료: 0,
  재고없음: 0,
  상품미도착: 0,
};

export const GOODS: GoodsItem[] = [
  {
    id: "g1",
    category: "오일",
    brand: "REPSOL",
    name: "GUARD LIQUIDO DE FRENOS DOT 4 브레이크오일 500ml",
    discountRate: 57,
    originalPrice: 15000,
    price: 6400,
    freeShipping: true,
  },
  {
    id: "g2",
    category: "오일",
    brand: "엑스오일",
    name: "SPECIAL SX SP C2 C3 5W-30 1L",
    discountRate: 64,
    originalPrice: 18000,
    price: 6500,
    freeShipping: true,
  },
  {
    id: "g3",
    category: "오일",
    brand: "FALCON",
    name: "[기획상품] REBOOT S API SQ ACEA C2/C3 6L",
    discountRate: 58,
    originalPrice: 69000,
    price: 28900,
    freeShipping: true,
  },
  {
    id: "g4",
    category: "오일",
    brand: "MANNOL",
    name: "마놀 MOS2 9991 엔진오일 첨가제 300ml",
    discountRate: 16,
    originalPrice: 10000,
    price: 8400,
    freeShipping: true,
  },
  {
    id: "g5",
    category: "세차용품",
    brand: "불멸의세차",
    name: "카샴푸 극광 슈퍼 물광 1L",
    discountRate: 32,
    originalPrice: 25000,
    price: 17000,
    freeShipping: true,
  },
  {
    id: "g6",
    category: "자동차용품",
    brand: "3M",
    name: "차량용 방향제 뉴카 향 2p",
    discountRate: 20,
    originalPrice: 12000,
    price: 9600,
    freeShipping: false,
  },
  {
    id: "g7",
    category: "공구",
    brand: "KTC",
    name: "에어 임팩트 렌치 1/2인치",
    discountRate: 12,
    originalPrice: 320000,
    price: 281600,
    freeShipping: false,
  },
  {
    id: "g8",
    category: "장비",
    brand: "한국공기",
    name: "2주식 리프트 4톤",
    discountRate: 8,
    originalPrice: 2800000,
    price: 2576000,
    freeShipping: false,
  },
  {
    id: "g9",
    category: "휠 액세서리",
    brand: "타이어존",
    name: "휠너트 세트 (20개입)",
    discountRate: 25,
    originalPrice: 40000,
    price: 30000,
    freeShipping: true,
  },
];

export const FAQ_CATEGORIES = [
  { id: "order", label: "주문/결제" },
  { id: "delivery", label: "배송관련" },
  { id: "cancel", label: "취소/반품/교환" },
  { id: "sell", label: "판매관련" },
  { id: "member", label: "회원관련" },
  { id: "etc", label: "기타" },
] as const;

export const FAQ_ITEMS: { id: string; category: string; q: string; a: string }[] = [
  {
    id: "fq1",
    category: "order",
    q: "주문 후 입금은 언제까지 해야 하나요?",
    a: "주문 후 24시간 이내 미입금 시 자동으로 주문이 취소됩니다. 출고시간 이전 입금 확인 시 당일 출고됩니다.",
  },
  {
    id: "fq2",
    category: "order",
    q: "세금계산서는 어떻게 발급받나요?",
    a: "마이페이지 > 세금계산서 내역에서 월별로 자동 집계되며, 익월 10일 이내 국세청 시스템으로 발행됩니다.",
  },
  {
    id: "fq3",
    category: "delivery",
    q: "배송은 얼마나 걸리나요?",
    a: "일반 배송은 입금 확인 후 1~2일, 당일직배송 지역은 당일 오후 도착이 가능합니다.",
  },
  {
    id: "fq4",
    category: "delivery",
    q: "제주/도서산간 지역도 배송되나요?",
    a: "가능하지만 추가 배송비가 발생할 수 있습니다. 결제 단계에서 자동 안내됩니다.",
  },
  {
    id: "fq5",
    category: "cancel",
    q: "입금 후 취소는 어떻게 하나요?",
    a: "주문내역/배송조회에서 출고 전 상태인 경우 직접 취소 신청이 가능합니다. 출고 후에는 반품 절차로 진행됩니다.",
  },
  {
    id: "fq6",
    category: "sell",
    q: "타이어를 판매하려면 어떻게 하나요?",
    a: "상단 GNB의 타이어판매 메뉴에서 재고를 등록하면 즉시 판매를 시작할 수 있습니다.",
  },
  {
    id: "fq7",
    category: "member",
    q: "회원정보는 어디서 수정하나요?",
    a: "우측 상단 프로필 영역의 회원정보수정 링크에서 이메일/연락처/정산계좌 등을 수정할 수 있습니다.",
  },
  {
    id: "fq8",
    category: "etc",
    q: "공장도가는 실시간으로 반영되나요?",
    a: "제조사 공급가 변경 시 공지사항에 안내 후 순차 반영됩니다.",
  },
];

export const UPDATE_LOGS = [
  { id: "u1", title: "2026.03.23 업데이트 (타이어 판매자 상품관리)", date: "2026-03-23" },
  { id: "u2", title: "2025.12.22 업데이트 (제주도 추가 배송비 적용)", date: "2025-12-22" },
  {
    id: "u3",
    title: "2025.09.15 업데이트 (판매자 이용 택배사 지정, 상품 형용코드 표시)",
    date: "2025-09-15",
  },
  { id: "u4", title: "2025.09.12 타이어존 업데이트 (출고시간 지정 기능 추가)", date: "2025-09-12" },
] as const;

export const REGIONS: Record<string, Record<string, string[]>> = {
  경기도: {
    화성시: ["기안동", "병점동", "반월동", "봉담읍"],
    수원시: ["영통동", "장안동", "권선동"],
    성남시: ["분당동", "수정동", "중원동"],
  },
  서울특별시: {
    강남구: ["역삼동", "삼성동", "대치동"],
    마포구: ["합정동", "망원동", "연남동"],
  },
  인천광역시: {
    남동구: ["구월동", "간석동"],
    연수구: ["송도동", "옥련동"],
  },
};

export const DIRECT_NOTICE =
  "타이어존으로 구매한 타이어, 오늘 받아보고 싶으시다면? 타이어 당일 직배송 주문으로~!";

export const WISH_SELLERS: WishSeller[] = [];

export const MY_LISTINGS: MyListing[] = [
  {
    id: "ml1",
    manufacturer: "한국",
    model: "Dynapro HPX (RA43)",
    width: 235,
    ratio: 55,
    rim: 19,
    dot: "2025",
    price: 189000,
    stock: 8,
    status: "판매중",
    registeredAt: "2026-06-02",
  },
  {
    id: "ml2",
    manufacturer: "금호",
    model: "MARSHAL MC55",
    width: 145,
    ratio: 80,
    rim: 13,
    dot: "2026",
    price: 64000,
    stock: 0,
    status: "품절",
    registeredAt: "2026-05-18",
  },
  {
    id: "ml3",
    manufacturer: "넥센",
    model: "N'Fera SU1",
    width: 205,
    ratio: 55,
    rim: 16,
    dot: "2025",
    price: 98000,
    stock: 15,
    status: "판매중",
    registeredAt: "2026-04-30",
  },
];
